### ISSUE TITLE
Focus should change to search text box on pressing '/'

### ISSUE THREAD

**Issue by vaidik** [chinchang/super-search#1]

**Comment by chinchang** [comment]
@vaidik Which browser is it not working on? Its implemented in code and working on Chrome.

**Comment by softvar** [comment]
Pressing `/` in Firefox opens `Quick Find` by default. https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

**Comment by chinchang** [comment]
I guess the only solution here is to use the alternate available shortcut: _ESC_ key. Stealing focus from the browser won't be possible and also not good UX.
