### ISSUE TITLE
posts.filter is not a function

### ISSUE THREAD

**Issue by oscarmcm** [chinchang/super-search#3]
Hey, nice lib but i have the following bug:

```
Uncaught TypeError: posts.filter is not a function
```

have some idea?

**Comment by chinchang** [comment]
This is probably due to some issue with your RSS feed. If you can post the link to your RSS feed, may be I can tell better.

**Comment by oscarmcm** [comment]
It's seems a bug with the number of post in the feed, I tested this with one post and cause the post.filter error but if your feed contain more than 3 post the bug don't appear.

by the way taking advantage of this issue, what are the parameters that you need to make the search? i tested this the categories and title but it's very variant.

**Comment by chinchang** [comment]
Currently the library uses `title` and `description` of every post to detect a match.
