### ISSUE TITLE
Error in line 91 -missing 'super-'

### ISSUE THREAD

**Issue by sunbliss** [chinchang/super-search#6]
https://github.com/chinchang/super-search/blob/master/super-search.js#L91
must be changed to `return '<li><a href="' + post.link + '">' + post.title + '<span class="super-search__result-date">' + d.toUTCString().replace(/.*(\d{2})\s+(\w{3})\s+(\d{4}).*/,'$2 $1, $3') + '</span></a></li>';`
otherwise the style breaks and the title is rendered without a space from the date...
Thank you for your great code!

EDIT:  For some reason the initialization script works for me only if I add 'super-' 

```
    searchSelector: '#js-super-search',
    inputSelector: '#js-super-search__input', 
    resultsSelector: '#js-super-search__results' 
```

**Comment by chinchang** [comment]
Yeah...that is a typo in the README. My bad. Will fix.
